version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: DockerfileSQL
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: tallerwebi-mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - tallerwebi-network
    restart: unless-stopped

  jetty-app:
    build:
      context: .
      dockerfile: DockerfileJetty
    container_name: tallerwebi-jetty
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - tallerwebi-network
    restart: unless-stopped
    env_file: .env
    environment:
      DB_HOST: ${APP_DB_HOST}
      DB_PORT: ${APP_DB_PORT}
      DB_NAME: ${APP_DB_NAME}
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}

volumes:
  mysql_data:
    driver: local

networks:
  tallerwebi-network:
    driver: bridge 